### ISSUE TITLE
Like/Dislike

### ISSUE THREAD

**Issue by ayoola00** [kishanankara/beautifulSoup#27]
We are looking for a like and dislike buttons for the playlist part of my website.

Location: Next to the play button

Size: same or very close to the play button

Functionality When clicked
have each button generates next to ea

**Comment by briankarUB** [comment]
Are these buttons supposed to do anything or just be there?

**Comment by yooil** [comment]
We are trying to create an algorithm which chooses songs based on user's preference (like, dislike), so when a user logs in next time, we can list better songs for the user. By the way, this is still a plan we are going to try to put it as an add-on feature.

**Comment by ayoola00** [comment]
They should just print something out when you click them

**Comment by ayoola00** [comment]
Also, the place you'll be placing the button will be in a node package.

**Comment by nlagrassa** [comment]
Thanks, Brian! Officially closing this issue based on #66 code. See #77 for production implementation of like/dislike functionality.

**Comment by briankarUB** [comment]
LOL
