### ISSUE TITLE
Home button & Emojis

### ISSUE THREAD

**Issue by yooil** [kishanankara/beautifulSoup#35]
Creating homebutton and emoji buttons on the Playlist page of our web app.

Location: Upper left-hand corner for homebutton and appropriate location emoji buttons ( it can be changed if teammate request ).

Size: Homebutton can be similar size of Jazz button on main home page ( size can be modified )
         Size of emoji buttons could be similar as button on main home page.

Style: Appropriate for the style and color scheme of the Playlist page

Functionality when clicked:
Redirect to our homepage (homebutton)
Direct to another mood based on emoji button (emojis)

For emojis, Clear the present mood and direct to another mood.

**Comment by nlagrassa** [comment]
Issue was meant to be closed with closing of pull request #71. Code provided by YongJi97 was not integrated into production code for reasons related to internal team communications that can be inquired about individually.

Thank you for your help, YongJi97!
