### ISSUE TITLE
Homepage takes forever to load

### ISSUE THREAD

**Issue by kishanankara** [kishanankara/beautifulSoup#38]
Browsers: Firefox, Chrome, Safari
The home page to the product [Upliftme](https://upliftme.herokuapp.com) takes a long time to load. The webpage size could possibly be large or the video is being buffered when webpage loads.

**Comment by ayoola00** [comment]
Can I get more examples?

**Comment by ayoola00** [comment]
FIx and pushed under the fixedvid branch

**Comment by nlagrassa** [comment]
Why was this reopened?

**Comment by kishanankara** [comment]
No pull request was made.

**Comment by nlagrassa** [comment]
Are you waiting for someone else to do it?

**Comment by kishanankara** [comment]
Did not look at the reference to the branch. Closing this issue now.
