### ISSUE TITLE
Misbehaving buttons for each track: Next, Previous, Repeat

### ISSUE THREAD

**Issue by nlagrassa** [kishanankara/beautifulSoup#39]
Browser used: Chrome Version 65.0.3325.181
Times 

What I did to cause the bug:
(1) After selecting a mood, I attempted to use the previous button and it toggled the play button to pause without affecting the track.

![screen shot 2018-03-28](https://user-images.githubusercontent.com/13890831/38056417-5fbfd314-32aa-11e8-8bcd-6d8608b1f107.png)

This happens for all tracks, every time I attempt it.

(2) Related, the Next, Previous, and Repeat buttons do not seem to have their intended functionality. The Next and Forward buttons cause the blue bar that tracks how much of the song has played flickers upon click, but does not affect how the song behaves during play. The Repeat button does not do anything at all. This also is true every time I attempt it.

In the image below, the song played all the way through with the repeat button engaged and it did not restart:

![screen shot 2018-03-28](https://user-images.githubusercontent.com/13890831/38056724-4909a7c0-32ab-11e8-8186-8aa5212aa2c2.png)

Suggestions:
(1) Check the event handler code for the previous button component in your React code. Upon click, something is telling the play button to toggle to a pause display. I do not think this is necessary.
(2) Consider removing these buttons. The user story of this project does not require repeat or playback functionality. When the song completes the user can still replay the track. You could also consider removing the next and repeat buttons and enabling the previous button to restart the current song, giving the user more control over the play experience of the song.

**Comment by ayoola00** [comment]
Understand will it be better to remove or implement the functionalities

**Comment by kishanankara** [comment]
Issue is fixed as new player is in place.

**Comment by kishanankara** [comment]
Since new player is in place these functions are no longer needed.
