### ISSUE TITLE
Resizing minor bug. [minor bug]

### ISSUE THREAD

**Issue by gauravav** [kishanankara/beautifulSoup#41]
When we resize the window with the web-app open, the mood buttons cutoff disabling me to scroll to the later mood button.
![issue](https://user-images.githubusercontent.com/36088481/38066503-4108104a-32d6-11e8-8ccf-8e305f53fa85.JPG)

**Comment by yooil** [comment]
Fixed in local repo. Currently, I am unable to push code in. I will push the code as soon as possible
