### ISSUE TITLE
Long song name makes play button unuseable

### ISSUE THREAD

**Issue by rmredder** [kishanankara/beautifulSoup#51]
Browser: Chrome

After selecting a mood and receiving a playlist I noticed that a song with an extremely long name made the text overlap the play button so that I could not use the play button.

<img width="375" alt="jazz" src="https://user-images.githubusercontent.com/31999343/38774113-3112a1d6-402e-11e8-9221-bef2d51be5cb.PNG">

**Comment by nlagrassa** [comment]
Thanks! Do you know how many characters come before the C in Caplen?

**Comment by rmredder** [comment]
I did not take a picture of the whole screen, but if you make your browser smaller you can reproduce this with shorter songs. 

![image](https://user-images.githubusercontent.com/31999343/38779241-b1e8116e-4093-11e8-87e9-e6f9fda24ade.png)
