### ISSUE TITLE
Only song clip playing

### ISSUE THREAD

**Issue by rmredder** [kishanankara/beautifulSoup#52]
Browser: Chrome

Only a clip of the song is being played. After testing 4 songs, it seems that every song does not start at the beginning and cuts out at approximately 30 seconds.

**Comment by nlagrassa** [comment]
This is a restriction placed by Spotify. Only premium users are given access to full songs.

**Comment by rmredder** [comment]
I do have a premium for students account, sorry should have mentioned that.
