### ISSUE TITLE
Bug with spotify

### ISSUE THREAD

**Issue by ArodyDel** [kishanankara/beautifulSoup#54]
I went to go authorized spotify instead of hitting confirm I press cancel and received this page.
Now I can't even use the website at all without seeing the spotify page. Below is a gif of what happen.

**GIF**
![Alt Text](https://media.giphy.com/media/62aF2YwGnarqDmDPGH/giphy.gif)

**Error Page:**
![bug](https://user-images.githubusercontent.com/11743195/38851692-b8b5429e-41e4-11e8-9503-3c69f5d7ebd4.png)

**Comment by kishanankara** [comment]
The issue has been identified and there is fix in place.

**Comment by kishanankara** [comment]
Closing this now #60 since it was fixed a long time ago.
