### ISSUE TITLE
Feature request: Add a refresh button

### ISSUE THREAD

**Issue by lonesai** [kishanankara/beautifulSoup#57]
After the user picks his or her mood and goes through the playlist the only way to get a new playlist is to go back to the home page and pick the mood again or manually refresh the page, if they desire more songs from that mood. By adding a button that generates a new playlist or something that tells the user to refresh the page if they want a new playlist would maybe make the transition more seamless after they have gone through all the songs.

**Comment by kishanankara** [comment]
If you hit the refresh button for the page itself, it actually does that.

**Comment by nlagrassa** [comment]
We added our own refresh button to the top-right corner of our playlist page so that users don't have to click their own browser refresh button to get a new list of songs. Thanks for the suggestion! (See merge #77 for code)
