### ISSUE TITLE
CSS/HTML fix on the welcome box.

### ISSUE THREAD

**Issue by briandoyle89** [kishanankara/beautifulSoup#62]
The text over-runs the div here a little bit, consider making this a bit larger!

![jazz-fix](https://user-images.githubusercontent.com/31046077/38908282-7a23e9a0-428d-11e8-9a5c-c3cfd81b6ada.jpeg)

**Comment by nlagrassa** [comment]
Fixed! We opted to remove the box entirely as it didn't really fit our intended product anyway. Thanks for reporting. (See merge #77)
