### ISSUE TITLE
Feature Request: The background color of the website is too bright to look at. 

### ISSUE THREAD

**Issue by KimDoggy** [kishanankara/beautifulSoup#63]
#63
The background color of the website was so bright and blinded my eyes. I did not feel comfortable but somehow dizzy if I looked at it for over 10 seconds. I suggest the development team change the background color and be careful of the color combination of different components of the website.

**Comment by yooil** [comment]
Ok, we will talk about this issue. Thanks for reporting

**Comment by nlagrassa** [comment]
Playlist now renders with more friendly colors (Merge #77). Thanks for raising the issue! We want our app to be clear, visible, and stabilizing to our seeing users. If you have other suggestions for how to improve the coloring to avoid inducing dizziness or physical discomfort, please let us know.
