### ISSUE TITLE
[Trivial Bug] Image of the album is too stretched out 

### ISSUE THREAD

**Issue by shallyguo** [kishanankara/beautifulSoup#73]
The image of the album in the playlist page is a bit too stretched out. This can be shown in the image below. 

![screen shot 2018-04-20 at 1 37 25 pm](https://user-images.githubusercontent.com/31744330/39065584-406a6fb2-44a0-11e8-9516-000c2511f940.png)

A suggestion would be to design the page such that the album image corresponds to its intended proportions.

**Comment by kishanankara** [comment]
We are working on a fix soon. be on lookout for updates.

**Comment by nlagrassa** [comment]
Fixed (see merge #77)! Album art appears at 50% width to reduce stretch and improve image clarity. Reduced fixed height as well to allow more playlist tracks to appear on screen at once. Thanks for reporting!
