### ISSUE TITLE
icon - Screen sync

### ISSUE THREAD

**Issue by kishanankara** [kishanankara/beautifulSoup#9]
The icons in the welcome page have to adjust automatically with the screen size.
Also make it viewable on the phone.

**Comment by nlagrassa** [comment]
Are we worrying about mobile compatibility?

**Comment by kishanankara** [comment]
Ideally, Because even on the browser if the screen adjusts we needs the icons to rearrange accordingly.

**Comment by yooil** [comment]
Completed
